#!/bin/bash

# Get timezone from user
timezone=$(dialog --stdout \
		--backtitle "Mee's Arch Setup" \
		--title "Select Timezone" \
		--fselect /usr/share/zoneinfo/ 16 60)

# Get hostname from user
hostname=$(dialog --stdout \
		--backtitle "Mee's Arch Setup" \
		--title "Hostname" \
		--inputbox "Enter the hostname" 8 60)


# Setup systemclock
timedatectl set-ntp true

# Bootstrap pacman and beginn system installation
pacstrap /mnt base base-devel bash-completion dialog git dhcpcd sudo

# Generate Fstab
genfstab -U /mnt >> /mnt/etc/fstab

# Change Root
arch-chroot /mnt
cd /root

# Setup install scripts
git clone https://github.com/mee4895/ArchSetup.git

# Setup timezone
ln -sf $timezone /etc/localtime
hwclock --systohc

# Setup localization
echo -e "\n# Autogenerated Entries by Mee's Arch Setup" >> /etc/locale.gen
echo "de_DE.UTF-8 UTF-8" >> /etc/locale.gen
echo "de_US.UTF-8 UTF-8" >> /etc/locale.gen
locale-gen

echo "LANG=en_US.UTF-8" >> /etc/locale.conf
echo "KEYMAP=de-latin1" >> /etc/vconsole.conf

# Setup network
echo -n "$hostname" >> /etc/hostname
cat >> /etc/hosts << EOF
127.0.0.1	localhost
::1			localhost
127.0.1.1	$hostname.local $hostname
EOF

systemctl enable dhcpcd
